name: Deploy to App Engine

# Controls when the workflow will run
on:
    push:
        branches: [main]
    pull_request:
        branches: [main]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    deploy:
        name: Deploying to Google Cloud
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Generate .env file
              id: generate_dotenv_file
              env:
                  DOTENV_FILE: ${{ secrets.DOTENV_FILE }}
              run: echo "$DOTENV_FILE" > .env

            - name: Deploy to App Engine
              id: deploy
              uses: google-github-actions/deploy-appengine@v0.2.0
              with:
                  deliverables: app.yaml
                  version: v1
                  project_id: ${{ secrets.GCP_PROJECT }}
                  credentials: ${{ secrets.GCP_CREDENTIALS }}

            - name: Test
              run: curl "${{ steps.deploy.outputs.url }}"
